'use client';
import {useEffect,useMemo,useState} from "react";
import {ChevronLeft,ChevronRight,Search,X,Utensils,NotebookPen,Trash2,Settings,Home,BookOpen,Plus} from "lucide-react";

type Meal={type:"dish"|"free";dishId?:string;text?:string};
type WeekDay={lunch?:Meal;dinner?:Meal};
type Data={dishes:{id:string;title:string;active:boolean}[];weeks:Record<string,Record<string,WeekDay>>;settings:{showWeekend:boolean}};
const initial:Data={dishes:[
{id:"d1",title:"Pasta al pesto",active:true},{id:"d2",title:"Pollo al forno",active:true},{id:"d3",title:"Insalata",active:true},{id:"d4",title:"Pizza",active:true},{id:"d5",title:"Risotto ai funghi",active:true},{id:"d6",title:"Cotoletta alla milanese",active:true},{id:"d7",title:"Insalata di tonno",active:true},{id:"d8",title:"Pasta al pomodoro",active:true},{id:"d9",title:"Lasagne alla bolognese",active:true}
],weeks:{},settings:{showWeekend:false}};
const days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const; const labels=["LUN","MAR","MER","GIO","VEN","SAB","DOM"];
const pad=(n:number)=>String(n).padStart(2,"0");
const startOfWeek=(input=new Date())=>{const d=new Date(input);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d};
const key=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const labelRange=(d:Date,weekend:boolean)=>{const e=new Date(d);e.setDate(d.getDate()+(weekend?6:4));const f=new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"long"});return `${f.format(d)} — ${f.format(e)}`};
const clone=<T,>(x:T):T=>structuredClone(x);

export default function MenuWeekly(){
 const [data,setData]=useState<Data>(initial); const [start,setStart]=useState(startOfWeek()); const [tab,setTab]=useState<"menu"|"dishes"|"settings">("menu");
 const [picker,setPicker]=useState<{day:string;meal:"lunch"|"dinner"}|null>(null); const [actions,setActions]=useState<{day:string;meal:"lunch"|"dinner"}|null>(null);
 const [search,setSearch]=useState(""); const [addOpen,setAddOpen]=useState(false); const [draft,setDraft]=useState(""); const [duplicate,setDuplicate]=useState(false);
 const [editFree,setEditFree]=useState<{day:string;meal:"lunch"|"dinner";text:string}|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem("menuweekly-data");if(raw)setData(JSON.parse(raw))}catch{}},[]);
 const persist=(next:Data)=>{setData(next);try{localStorage.setItem("menuweekly-data",JSON.stringify(next))}catch{}};
 const weekKey=key(start); const week=data.weeks[weekKey]??{}; const visible=data.settings.showWeekend?7:5;
 const dishes=useMemo(()=>data.dishes.filter(x=>x.active&&x.title.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.title.localeCompare(b.title,"it")),[data.dishes,search]);
 const meal=(day:string,slot:"lunch"|"dinner")=>week[day]?.[slot];
 const title=(m?:Meal)=>m?.type==="dish"?data.dishes.find(d=>d.id===m.dishId)?.title||"Piatto non disponibile":"";
 const setMeal=(day:string,slot:"lunch"|"dinner",value?:Meal)=>{const next=clone(data);next.weeks[weekKey]??={};next.weeks[weekKey][day]??={};if(value)next.weeks[weekKey][day][slot]=value;else delete next.weeks[weekKey][day][slot];persist(next)};
 const chooseDish=(id:string)=>{if(picker){setMeal(picker.day,picker.meal,{type:"dish",dishId:id});setPicker(null)}};
 const openCell=(day:string,mealSlot:"lunch"|"dinner")=>{const m=meal(day,mealSlot); if(!m){setSearch("");setPicker({day,meal:mealSlot});return}setActions({day,meal:mealSlot})};
 const createDish=()=>{const t=draft.trim();if(!t)return;if(data.dishes.some(d=>d.active&&d.title.toLowerCase()===t.toLowerCase())){setDuplicate(true);return}const next=clone(data);next.dishes.push({id:crypto.randomUUID(),title:t,active:true});persist(next);setDraft("");setAddOpen(false)};
 return <div className="app">
  <header className="header"><div className="brand"><span className="brandIcon">🍴</span><span><b>Menu</b>Weekly</span></div>{tab==="menu"&&<div className="weekNav"><button className="navBtn" onClick={()=>{const d=new Date(start);d.setDate(d.getDate()-7);setStart(d)}}><ChevronLeft size={20}/></button><div><div className="weekTitle">{labelRange(start,data.settings.showWeekend)}</div>{key(startOfWeek())===weekKey&&<div className="weekSub">Settimana corrente</div>}</div><button className="navBtn" onClick={()=>{const d=new Date(start);d.setDate(d.getDate()+7);setStart(d)}}><ChevronRight size={20}/></button></div>}</header>
  {tab==="menu"&&<main className="content"><div className="table"><div className="tableHead"><div></div><div className="headCell">☀️ Pranzo</div><div className="headCell">🌙 Cena</div></div>{days.slice(0,visible).map((day,i)=><div className="dayRow" key={day}><div className="dayCell">{labels[i]}</div>{(["lunch","dinner"] as const).map(slot=>{const m=meal(day,slot);return <div className="mealCell" key={slot}><button className={`mealCard ${m?.type||"empty"}`} onClick={()=>openCell(day,slot)}>{m?(m.type==="free"?<><NotebookPen size={14}/>{m.text}</>:title(m)):"+"}</button></div>})}</div>)}</div><div className="bottomBar"><button className="openDishes" onClick={()=>{setSearch("");setPicker({day:"monday",meal:"lunch"})}}>☷ &nbsp; I miei piatti</button></div></main>}
  {tab==="dishes"&&<main className="dishesPage"><div className="pageHeader"><BookOpen size={22}/><h1>I miei piatti</h1></div><div className="searchWrap"><Search className="searchIcon" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca un piatto..." />{search&&<button className="clearBtn" onClick={()=>setSearch("")}><X size={18}/></button>}</div><button className="newBtn" onClick={()=>setAddOpen(true)}><Plus size={18}/> Nuovo piatto</button><div className="managedList">{dishes.map(d=><div className="managedItem" key={d.id}><span>{d.title}</span><span className="more">⋮</span></div>)}</div></main>}
  {tab==="settings"&&<main className="settingsPage"><div className="pageHeader"><Settings size={22}/><h1>Impostazioni</h1></div><div className="settingsCard"><div className="settingRow"><div><div className="settingTitle">Mostra weekend</div><div className="settingDesc">Se attivato, verranno mostrati anche sabato e domenica nel menu settimanale.</div></div><button aria-label="Mostra weekend" className={`switch ${data.settings.showWeekend?"on":""}`} onClick={()=>persist({...data,settings:{...data.settings,showWeekend:!data.settings.showWeekend}})} /></div></div></main>}
  <footer className="footer"><button className={`footerBtn ${tab==="menu"?"active":""}`} onClick={()=>setTab("menu")}><Home size={20}/><span>Menu</span></button><button className={`footerBtn ${tab==="dishes"?"active":""}`} onClick={()=>setTab("dishes")}><BookOpen size={20}/><span>I miei piatti</span></button><button className={`footerBtn ${tab==="settings"?"active":""}`} onClick={()=>setTab("settings")}><Settings size={20}/><span>Impostazioni</span></button></footer>
  {picker&&<div className="overlay" onClick={()=>setPicker(null)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheetHandle"/><div className="sheetTitle"><span>Seleziona un piatto</span><button onClick={()=>setPicker(null)}><X size={20}/></button></div><div className="searchWrap"><Search className="searchIcon" size={18}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca un piatto..." />{search&&<button className="clearBtn" onClick={()=>setSearch("")}><X size={18}/></button>}</div><div className="dishList">{dishes.map(d=><button key={d.id} className="dishItem" onClick={()=>chooseDish(d.id)}>{d.title}</button>)}</div></div></div>}
  {actions&&<div className="overlay" onClick={()=>setActions(null)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheetTitle"><span>{labels[days.indexOf(actions.day as typeof days[number])]} · {actions.meal==="lunch"?"Pranzo":"Cena"}</span><button onClick={()=>setActions(null)}><X size={20}/></button></div><div className={`mealCard ${meal(actions.day,actions.meal)?.type||""}`}>{meal(actions.day,actions.meal)?.type==="free"?<><NotebookPen size={15}/>{meal(actions.day,actions.meal)?.text}</>:title(meal(actions.day,actions.meal))}</div><div className="actions"><button className="actionBtn" onClick={()=>{setSearch("");setPicker(actions);setActions(null)}}><Utensils size={18}/> Cambia piatto</button>{meal(actions.day,actions.meal)?.type==="free"&&<button className="actionBtn" onClick={()=>{setEditFree({day:actions.day,meal:actions.meal,text:meal(actions.day,actions.meal)?.text||""});setActions(null)}}><NotebookPen size={18}/> Modifica testo</button>}<button className="actionBtn" onClick={()=>{setMeal(actions.day,actions.meal);setActions(null)}}><Trash2 size={18}/> Svuota cella</button></div><button className="actionBtn" onClick={()=>setActions(null)} style={{justifyContent:"center"}}>Annulla</button></div></div>}
  {editFree&&<div className="modalWrap"><div className="modal"><h3>Modifica testo</h3><label className="fieldLabel">Cosa mangerai?</label><input className="field" autoFocus value={editFree.text} onChange={e=>setEditFree({...editFree,text:e.target.value})}/><div className="modalBtns"><button className="modalBtn primary" onClick={()=>{setMeal(editFree.day,editFree.meal,{type:"free",text:editFree.text.trim()});setEditFree(null)}}>Salva</button><button className="modalBtn" onClick={()=>setEditFree(null)}>Annulla</button></div></div></div>}
  {addOpen&&<div className="modalWrap"><div className="modal"><h3>Nuovo piatto</h3><label className="fieldLabel">Nome del piatto</label><input className="field" autoFocus value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")createDish()}}/><div className="modalBtns"><button className="modalBtn primary" onClick={createDish}>Salva</button><button className="modalBtn" onClick={()=>setAddOpen(false)}>Annulla</button></div></div></div>}
  {duplicate&&<div className="modalWrap"><div className="modal"><h3>Piatto già esistente</h3><p>Il piatto “{draft.trim()}” è già presente nell'anagrafica.</p><button className="modalBtn primary" style={{width:"100%"}} onClick={()=>setDuplicate(false)}>OK</button></div></div>}
 </div>;
}
